MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    NUM_CLASSES: 21
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
DATASETS:
  TRAIN: ("ycb_video_train",)
  TEST: ("ycb_video_keyframe",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
  ASPECT_RATIO_GROUPING: False
  NUM_WORKERS: 0
SOLVER:
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.0001
  STEPS: (120000,)
  MAX_ITER: 160000
  IMS_PER_BATCH: 2
TRAIN:
  SCALES_BASE: (1.0,)
  MAX_ITERS_PER_EPOCH: 20000
  CLASSES: (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 21) # no large clamp
  USE_FLIPPED: False
  CHROMATIC: True
  ADD_NOISE: True
  VISUALIZE: False
  # synthetic data
  SYNTHESIZE: True
  SYN_RATIO: 5
  SYN_BACKGROUND_SPECIFIC: False
  SYN_BACKGROUND_SUBTRACT_MEAN: True
  SYN_SAMPLE_OBJECT: True
  SYN_SAMPLE_POSE: False
  SYN_MIN_OBJECT: 5
  SYN_MAX_OBJECT: 8
  SYN_TNEAR: 0.5
  SYN_TFAR: 1.6
  SYN_BOUND: 0.15
  SYN_STD_ROTATION: 15
  SYN_STD_TRANSLATION: 0.05
TEST:
  SCALES_BASE: (1.0,)
  VISUALIZE: True
  SYNTHESIZE: False
